/**
 * Exercise library loader and pure query helpers.
 *
 * The library JSON (public/data/exercise-library.json, ~1.7MB, 1324 exercises)
 * is generated by scripts/build-exercise-library.mjs and served as a static
 * asset. loadExerciseLibrary() fetches it once and caches the promise in
 * module scope; all query helpers are pure functions over the loaded array so
 * they are trivially testable and usable in batch/PDF generation pipelines.
 */

import type {
  ExerciseMediaUrls,
  LibraryExercise,
  LibraryFilters,
} from "../types";

const LIBRARY_URL = "/data/exercise-library.json";

// Media © Gymvisual (gymvisual.com) — self-hosted on Cloudflare R2
// (bucket jcv-exercise-media) pending Gymvisual license for production use.
const MEDIA_BASE_URL = "https://media.jcv24fitness.com/";

let libraryPromise: Promise<LibraryExercise[]> | null = null;

/**
 * Fetch the exercise library once and cache it for the lifetime of the module.
 * Concurrent callers share the same in-flight request. A failed fetch clears
 * the cache so a later call can retry.
 */
export function loadExerciseLibrary(): Promise<LibraryExercise[]> {
  if (!libraryPromise) {
    libraryPromise = fetch(LIBRARY_URL)
      .then((res) => {
        if (!res.ok) {
          throw new Error(
            `Failed to load exercise library: ${res.status} ${res.statusText}`
          );
        }
        return res.json() as Promise<LibraryExercise[]>;
      })
      .catch((error) => {
        libraryPromise = null;
        throw error;
      });
  }
  return libraryPromise;
}

/** Test-only escape hatch to reset the module-scope cache. */
export function resetExerciseLibraryCache(): void {
  libraryPromise = null;
}

/** Lowercase and strip diacritics so "extensión" matches "extension". */
function normalize(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

/**
 * Case- and accent-insensitive substring search over exercise names.
 * An empty/whitespace query returns the full list.
 */
export function searchExercises(
  list: LibraryExercise[],
  query: string
): LibraryExercise[] {
  const normalized = normalize(query.trim());
  if (!normalized) return list;
  return list.filter((ex) => normalize(ex.name).includes(normalized));
}

/**
 * Filter by any combination of category, equipment, and target.
 * Omitted filters match everything.
 */
export function filterExercises(
  list: LibraryExercise[],
  filters: LibraryFilters
): LibraryExercise[] {
  const { category, equipment, target } = filters;
  return list.filter(
    (ex) =>
      (category === undefined || ex.category === category) &&
      (equipment === undefined || ex.equipment === equipment) &&
      (target === undefined || ex.target === target)
  );
}

/** Find a single exercise by its dataset id (e.g. "0001"). */
export function getLibraryExercise(
  list: LibraryExercise[],
  id: string
): LibraryExercise | undefined {
  return list.find((ex) => ex.id === id);
}

/**
 * Extract the dataset id from a media URL or relative path whose filename is
 * prefixed with the id, e.g. ".../images/0043-qXTaZnJ.jpg" -> "0043".
 * Returns undefined when the filename does not match the dataset pattern.
 */
export function extractDatasetId(url: string): string | undefined {
  const filename = url.split("/").pop() ?? "";
  const match = filename.match(/^(\d+)-/);
  return match ? match[1] : undefined;
}

/**
 * Derive the MP4 transcode and WebP poster URLs from a GIF URL (or relative
 * path), e.g. ".../videos/0043-qXTaZnJ.gif" ->
 * { mp4: ".../videos-mp4/0043-qXTaZnJ.mp4", poster: ".../posters/0043-qXTaZnJ.webp" }.
 * The transcodes live in sibling R2 prefixes and share the GIF's basename
 * (see scripts/transcode-exercise-media.sh).
 */
export function deriveMp4Media(gifUrl: string): { mp4: string; poster: string } {
  const filename = gifUrl.split("/").pop() ?? "";
  const base = filename.replace(/\.gif$/i, "");
  const prefix = gifUrl
    .slice(0, gifUrl.length - filename.length)
    .replace(/videos\/$/, "");
  return {
    mp4: `${prefix}videos-mp4/${base}.mp4`,
    poster: `${prefix}posters/${base}.webp`,
  };
}

/** Absolute media URLs for an exercise (image jpg, animated gif, mp4 + poster). */
export function getMediaUrls(ex: LibraryExercise): ExerciseMediaUrls {
  const gif = `${MEDIA_BASE_URL}${ex.gif}`;
  return {
    image: `${MEDIA_BASE_URL}${ex.image}`,
    gif,
    ...deriveMp4Media(gif),
  };
}
