/**
 * Types for the exercise library (public/data/exercise-library.json),
 * generated by scripts/build-exercise-library.mjs from the
 * hasaneyldrm/exercises-dataset (1324 exercises).
 *
 * Union values are derived from the actual dataset — regenerate the JSON
 * with the script and update these if the upstream dataset changes.
 */

/** Supported UI languages for exercise content. */
export type Lang = "es" | "en";

/** A text value available in both Spanish and English. */
export type BilingualText = Record<Lang, string>;

/** A step list available in both Spanish and English. */
export type BilingualSteps = Record<Lang, string[]>;

export type LibraryCategory =
  | "back"
  | "cardio"
  | "chest"
  | "lower arms"
  | "lower legs"
  | "neck"
  | "shoulders"
  | "upper arms"
  | "upper legs"
  | "waist";

export type LibraryEquipment =
  | "assisted"
  | "band"
  | "barbell"
  | "body weight"
  | "bosu ball"
  | "cable"
  | "dumbbell"
  | "elliptical machine"
  | "ez barbell"
  | "hammer"
  | "kettlebell"
  | "leverage machine"
  | "medicine ball"
  | "olympic barbell"
  | "resistance band"
  | "roller"
  | "rope"
  | "skierg machine"
  | "sled machine"
  | "smith machine"
  | "stability ball"
  | "stationary bike"
  | "stepmill machine"
  | "tire"
  | "trap bar"
  | "upper body ergometer"
  | "weighted"
  | "wheel roller";

export type LibraryTarget =
  | "abductors"
  | "abs"
  | "adductors"
  | "biceps"
  | "calves"
  | "cardiovascular system"
  | "delts"
  | "forearms"
  | "glutes"
  | "hamstrings"
  | "lats"
  | "levator scapulae"
  | "pectorals"
  | "quads"
  | "serratus anterior"
  | "spine"
  | "traps"
  | "triceps"
  | "upper back";

export interface LibraryExercise {
  /** Dataset id, e.g. "0001". Unique. */
  id: string;
  /** English exercise name, e.g. "3/4 sit-up". */
  name: string;
  category: LibraryCategory;
  /** Same value set as category in the current dataset. */
  body_part: LibraryCategory;
  equipment: LibraryEquipment;
  target: LibraryTarget;
  /** Up to 3 secondary muscles. */
  secondary_muscles: string[];
  /** Instructions as a single paragraph, per language. */
  instructions: BilingualText;
  /** Step-by-step instructions, per language. */
  instruction_steps: BilingualSteps;
  /** Relative path, e.g. "images/0001-2gPfomN.jpg". Use getMediaUrls() for the full URL. */
  image: string;
  /** Relative path, e.g. "videos/0001-2gPfomN.gif". Use getMediaUrls() for the full URL. */
  gif: string;
}

export interface LibraryFilters {
  category?: LibraryCategory;
  equipment?: LibraryEquipment;
  target?: LibraryTarget;
}

export interface ExerciseMediaUrls {
  image: string;
  gif: string;
}
